# Generated by Django 3.2.7 on 2021-09-21 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradersCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example currency,crypo,futures', max_length=50, verbose_name='Traders Category name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='dashboard.TradersCategory')),
                ('trader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Traders Name')),
            ],
            options={
                'verbose_name': 'Trader',
                'verbose_name_plural': 'Traders',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(choices=[('Dow Jones', 'Dow Jones'), ('S&P 500', 'S&P 500'), ('Nasdaq', 'Nasdaq'), ('Small Cap 2000', 'Small Cap 2000'), ('S&P 500 VIX', 'S&P 500 VIX'), ('DAX', 'DAX'), ('FTSE 100', 'FTSE 100'), ('CAC 40', 'CAC 40'), ('S&P/BMV IPC', 'S&P/BMV IPC'), ('Euro Stoxx 50', 'Euro Stoxx 50')], max_length=50, verbose_name='Pair Traded')),
                ('lots_traded', models.DecimalField(decimal_places=6, max_digits=12)),
                ('proit_n_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pips', models.DecimalField(decimal_places=6, max_digits=12)),
                ('traded_date', models.DateTimeField(auto_now_add=True)),
                ('trader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.trader', verbose_name='Trader')),
            ],
        ),
        migrations.CreateModel(
            name='FuturesSubcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(choices=[('6B', 'BRITISH POUND FUTURES'), ('6E ', 'EURO FX FUTURES'), ('6A', 'AUSRALIAN DOLLAR FUTURES'), ('6J', 'JAPANESE YEN FUTURES'), ('6C', 'CANADIAN DOLLAR FUTURES'), ('6S', 'SWISS FRANC FUTURES'), ('GC', 'GOLD FUTURES'), ('CL', 'CRUDE OIL FUTURES'), ('RI', 'RTS INDEX FUTURES'), ('YM', 'E- MINI DOW ($5) FUTURES')], max_length=50, verbose_name='Instrument Traded')),
                ('proit_n_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pips', models.DecimalField(decimal_places=6, max_digits=12)),
                ('traded_date', models.DateTimeField(auto_now_add=True)),
                ('trader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.trader', verbose_name='Trader')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(choices=[('EUR/USD', 'EUR/USD'), ('USD/JPY', 'USD/JPY'), ('GBP/USD', 'GBP/USD'), ('USD/CHF', 'USD/CHF'), ('EUR/CHF', 'EUR/CHF'), ('EUR/JPY', 'EUR/JPY'), ('GBP/EUR', 'GBP/EUR'), ('GBP/JPY', 'GBP/JPY'), ('GBP/CHF', 'GBP/CHF'), ('CHF/JPY', 'CHF/JPY'), ('USD/SEK', 'USD/SEK'), ('EUR/HUF', 'EUR/HUF'), ('AUD/USD', 'AUD/USD'), ('AUD/JPY', 'AUD/JPY'), ('AUD/NZD', 'AUD/NZD'), ('AUD/CAD', 'AUD/CAD'), ('USD/CAD', 'USD/CAD'), ('USD/NOK', 'USD/NOK'), ('USD/RUB', 'USD/RUB'), ('USD/ZAR', 'USD/ZAR'), ('EUR/NOK', 'EUR/NOK'), ('EUR/RUB', 'EUR/RUB'), ('GBP/ZAR', 'GBP/ZAR')], max_length=50, verbose_name='Pair Traded')),
                ('lots_traded', models.DecimalField(decimal_places=6, max_digits=12)),
                ('proit_n_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pips', models.DecimalField(decimal_places=6, max_digits=12)),
                ('traded_date', models.DateTimeField(auto_now_add=True)),
                ('trader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.trader', verbose_name='Trader')),
            ],
        ),
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypo_name', models.CharField(choices=[('BTC', 'BITCOIN'), ('ETH ', 'ETHEREUM'), ('USDT', 'TETHER'), ('ADA', 'CARDANO'), ('BNB', 'BINANCE COIN'), ('XRP', 'XRP'), ('SOL', 'SOLANA'), ('USDC', 'USD COIN'), ('DOT', 'POLKADOT'), ('DOGE', 'DOGECOIN')], max_length=50, verbose_name='Crypto name')),
                ('daily_change', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Daily change in %')),
                ('traded_date', models.DateTimeField(auto_now_add=True)),
                ('trader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.trader', verbose_name='Trader')),
            ],
        ),
    ]
