# Generated by Django 3.2.7 on 2021-09-21 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crypto',
            options={'ordering': ['-traded_date'], 'verbose_name': 'Crypto currency', 'verbose_name_plural': 'Crypto currencies'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-traded_date'], 'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='futuressubcription',
            options={'ordering': ['-traded_date'], 'verbose_name': 'Future', 'verbose_name_plural': 'Futures'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-traded_date'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterModelOptions(
            name='traderscategory',
            options={'verbose_name': 'Trading category', 'verbose_name_plural': 'Trading categories '},
        ),
        migrations.CreateModel(
            name='TraderBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('startingbalance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('endbalance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('trader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Traders Name')),
            ],
        ),
    ]
