# Generated by Django 3.2.7 on 2021-09-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210921_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderbalance',
            name='endbalance',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8, null=True),
        ),
    ]
