# Generated by Django 3.2.7 on 2022-02-21 10:21

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(editable=False, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='blog')),
                ('cover', models.ImageField(default='cover.png', upload_to='cover/', verbose_name='News Cover')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='slug')),
                ('brief', models.TextField()),
                ('content', django_quill.fields.QuillField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='Published Date')),
                ('category', models.ManyToManyField(to='blog.Category')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
